'use client'

import { Message } from '@/types/message'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Copy, Pencil, Trash2, Check, Clock, Mail, ChevronDown, ChevronUp, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { formatDistanceToNow } from 'date-fns'

interface MessageCardProps {
  message: Message
  onCopy: (messageId: string) => Promise<void>
  onEdit: (message: Message) => void
  onDelete: (messageId: string) => Promise<void>
  disabled?: boolean
  cached?: boolean
}

const channelConfig: Record<string, { label: string; className: string }> = {
  linkedin: { label: 'LinkedIn', className: 'bg-blue-100 text-blue-800 dark:bg-blue-900/50 dark:text-blue-300' },
  whatsapp: { label: 'WhatsApp', className: 'bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-300' },
  email: { label: 'Email', className: 'bg-orange-100 text-orange-800 dark:bg-orange-900/50 dark:text-orange-300' }
}

const sourceConfig: Record<string, { label: string; className: string }> = {
  manual: { label: 'Manual', className: 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300' },
  ai: { label: 'AI Generated', className: 'bg-purple-100 text-purple-800 dark:bg-purple-900/50 dark:text-purple-300' }
}

export function MessageCard({ message, onCopy, onEdit, onDelete, disabled, cached }: MessageCardProps) {
  const [copied, setCopied] = useState(false)
  const [isDeleting, setIsDeleting] = useState(false)
  const [showReasons, setShowReasons] = useState(false)

  const channel = channelConfig[message.channel] || channelConfig.linkedin
  const source = sourceConfig[message.generation_source] || sourceConfig.manual

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(message.content)
      setCopied(true)
      await onCopy(message.id)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      setCopied(false)
    }
  }

  const handleDelete = async () => {
    setIsDeleting(true)
    try {
      await onDelete(message.id)
    } finally {
      setIsDeleting(false)
    }
  }

  const statusConfig: Record<string, { label: string; className: string }> = {
    draft: { label: 'Draft', className: 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300' },
    ready: { label: 'Ready', className: 'bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-300' },
    failed: { label: 'Failed', className: 'bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-300' },
    archived: { label: 'Archived', className: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/50 dark:text-yellow-300' }
  }

  const statusBadge = statusConfig[message.status] || statusConfig.draft

  const lastCopiedText = message.last_copied_at 
    ? formatDistanceToNow(new Date(message.last_copied_at), { addSuffix: true })
    : 'never'

  return (
    <div className={`group rounded-xl border bg-card p-5 space-y-4 transition-all hover:shadow-md ${message.status === 'failed' ? 'border-destructive' : ''}`}>
      {/* Drawer-style Header strictly formatted */}
      <div className="flex flex-col space-y-2 pb-4 border-b">
        <div className="flex items-start justify-between">
          <h4 className="font-semibold text-foreground text-lg flex items-center gap-2">
            Message Preview
            {message.status === 'failed' && <Badge variant="destructive">Failed</Badge>}
            {message.is_outdated && <Badge variant="outline" className="text-orange-500 border-orange-200">Outdated</Badge>}
          </h4>
          <Badge className={channel.className}>{channel.label}</Badge>
        </div>
        
        {message.generation_source === 'ai' && (
          <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-muted-foreground mt-2 bg-muted/30 p-3 rounded-lg border">
            <span className="flex items-center gap-1"><Sparkles className="w-3.5 h-3.5 text-primary" /> Generated by: {message.ai_provider ? message.ai_provider.charAt(0).toUpperCase() + message.ai_provider.slice(1) : message.ai_model}</span>
            <span>Prompt Version: {message.prompt_version}</span>
            <span>Quality: {message.quality_label ? message.quality_label.charAt(0).toUpperCase() + message.quality_label.slice(1) : 'Unknown'}</span>
            <span>Characters: {message.character_count}</span>
            <span>Cost: ${message.estimated_cost_usd ? message.estimated_cost_usd.toFixed(4) : '0.0000'}</span>
            <span>Generation Time: {message.generation_duration_ms ? (message.generation_duration_ms / 1000).toFixed(2) : '?'}s</span>
          </div>
        )}
      </div>

      {/* Failure State */}
      {message.status === 'failed' && (
        <div className="bg-destructive/10 p-3 rounded-lg text-sm text-destructive border border-destructive/20">
          <p className="font-semibold">Generation Failed</p>
          <p className="mt-1">Reason: {message.generation_error || 'Unknown Error'}</p>
        </div>
      )}

      {/* Content */}
      <p className="text-sm leading-relaxed whitespace-pre-wrap text-foreground py-2 break-words max-w-full overflow-hidden">
        {message.content}
      </p>

      {/* Quality Reasons Expandable */}
      {message.quality_reasons && message.quality_reasons.length > 0 && (
        <div className="bg-muted/50 rounded-md border text-sm">
          <button 
            onClick={() => setShowReasons(!showReasons)}
            className="flex items-center justify-between w-full p-2 text-muted-foreground hover:text-foreground transition-colors"
          >
            <span className="font-medium text-xs">Why this score?</span>
            {showReasons ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </button>
          
          {showReasons && (
            <div className="p-3 pt-0 border-t space-y-2">
              {message.quality_reasons.map((r: any, idx: number) => (
                <div key={idx} className="flex items-start gap-2">
                  <span className="mt-0.5">{r.passed ? '✓' : '•'}</span>
                  <div>
                    <p className={`font-medium ${r.passed ? 'text-green-600 dark:text-green-400' : 'text-yellow-600 dark:text-yellow-400'}`}>
                      {r.rule}
                    </p>
                    <p className="text-muted-foreground text-xs">{r.description}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Footer: Analytics and Actions */}
      {/* Actions: Copy, Launch Email, LinkedIn, Edit, Archive, Delete */}
      <div className="flex flex-wrap items-center justify-between pt-4 border-t gap-4">
        <div className="text-xs text-muted-foreground">
          Last copied: {lastCopiedText}
        </div>
        
        <div className="flex flex-wrap items-center gap-2">
          {message.channel === 'email' && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                const encodedSubject = encodeURIComponent('Professional Opportunity')
                const encodedBody = encodeURIComponent(message.content.substring(0, 5000))
                window.location.href = `mailto:?subject=${encodedSubject}&body=${encodedBody}`
              }}
              disabled={disabled}
              className="gap-2"
            >
              <Mail className="w-4 h-4 text-orange-500" /> Launch Email
            </Button>
          )}
          {message.channel === 'linkedin' && (
            <Button variant="outline" size="sm" className="gap-2 text-blue-600">
              <Sparkles className="w-4 h-4" /> LinkedIn
            </Button>
          )}
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopy}
            disabled={disabled}
            className="gap-2"
          >
            {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied!' : 'Copy'}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => onEdit(message)}
            disabled={disabled}
            className="gap-2"
          >
            <Pencil className="w-4 h-4 text-primary" /> Edit
          </Button>
          <Button
            variant="outline"
            size="sm"
            disabled={disabled}
            className="gap-2 text-amber-500 hover:text-amber-600"
          >
            <ChevronDown className="w-4 h-4" /> Archive
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleDelete}
            disabled={isDeleting || disabled}
            className="gap-2 text-destructive hover:text-destructive"
          >
            <Trash2 className="w-4 h-4" /> Delete
          </Button>
        </div>
      </div>
    </div>
  )
}
